# TOÁN ỨNG DỤNG VÀ THỐNG KÊ

## Diagonalizable matrix

---

**Thông Tin Sinh Viên**
- MSSV: 22120017
- Họ tên: Trương Tiến Anh
- Lớp: Chiều thứ 7

## Giải thuật Diagonalizable matrix (A)
1. Giải phương trinh đặc trưng det(A−λI)=0 tìm các giá trị riêng của A
2. Ứng với mỗi giá trị riêng, tìm một cơ sở cho không gian riêng Vλ
3. Xét hệ B' gồm tát cả các vector riêng tạo thành cơ sở cho các không gian riêng nhận được ở Bước 2
- Nếu số phần tử B' bằng n (tức: dim(Vλ)=n) thì A chéo hóa được. Ma trận P chéo hóa ma trận A chính là ma trận đổi cơ sở chính tắc từ B sang B'
- Nếu số phần tử của B' < n, nghĩa là sigma(dimVλ) < n thì A không chéo hóa được
4. Ma trận làm chéo hóa A cần tìm là ma trận P có các cột là các vector riêng tìm được


## Bài 1) Cho A là ma trận có thể chéo hóa được. Sinh viên viết chương trình tìm ma trận chéo P, P-1 và ma trận đường chéo D, biết rằng A = PDP-1. 

In [1]:
import numpy as np

In [9]:

def eigen_power_iteration(A, n_iter=1000, eps=1e-5):
    # Khởi tạo vector ngẫu nhiên
    b_k = np.random.rand(A.shape[1])
    b_k_pre = np.zeros(A.shape[1])

    # Tìm vector riêng
    for _ in range(int(n_iter)):
        # Tính tích ma trận theo vector riêng
        numerator = np.dot(A, b_k)
        denominator = np.linalg.norm(numerator)
        
        b_k = numerator / denominator
        
        # Dừng khi sự thay đổi của vector trước và vector sau không đáng kể
        if np.all(np.abs(b_k - b_k_pre) < eps):
            break
        
        b_k_pre = b_k
        
    # Tìm trị riêng (Rayleigh quotient iteration)
    lamb = ((b_k @ A) @ b_k) / (b_k @ b_k)

    return lamb, b_k

def my_eigens(A, n_iter=1000, eps=1e-5):
    eigenvalues = []
    eigenvectors = []
    
    n_rows = A.shape[0]
    
    for _ in range(n_rows):
        lamb, b_k = eigen_power_iteration(A, n_iter, eps)
        
        eigenvalues.append(lamb)
        eigenvectors.append(b_k)
        
        # Hotelling’s deflation
        b_k = b_k.reshape(n_rows, -1)
        A = A - (lamb / np.square(np.linalg.norm(b_k))) * (b_k @ b_k.T)
        
    return np.array(eigenvalues), np.array(eigenvectors).T

def matrix_diag_from_power_iteration(A):
    # Sử dụng thuật toán Power Iteration để tìm trị riêng và vector riêng
    eigenvalues, eigenvectors = my_eigens(A)
    
    P_matrix = eigenvectors
    P_inv_matrix = np.linalg.inv(P_matrix)
    D_matrix = np.diag(eigenvalues)
    
    return P_matrix, D_matrix, P_inv_matrix

if __name__=="__main__":
    # Nhập ma trận A
    n = int(input('Nhập N: '))
    A = np.zeros((n, n))
    print(f'Nhập ma trận A[{n}x{n}]:')
    for i in range(n):
        for j in range(n):
            A[i][j] = float(input(f'a[{i}][{j}] = '))
    
    print('Ma trận A:')
    print(A)
    
    # Tính toán ma trận chéo, ma trận đường chéo và ma trận nghịch đảo của ma trận chéo
    P, D, P_inv = matrix_diag_from_power_iteration(A)
    print('Ma trận chéo P:')
    print(P)
    print('Ma trận đường chéo D:')
    print(D)
    print('Ma trận nghịch đảo P_inv:')
    print(P_inv)
    
    # Khôi phục lại ma trận A
    A_reconstructed = np.dot(np.dot(P, D), P_inv)
    print('Ma trận A khôi phục từ P, D, và P_inv:')
    print(A_reconstructed)


Nhập ma trận A[3x3]:
Ma trận A:
[[ 3. -2.  0.]
 [-2.  3.  0.]
 [ 0.  0.  5.]]
Ma trận chéo P:
[[-5.03291999e-01 -4.96684630e-01  7.07112232e-01]
 [ 5.03293636e-01  4.96686075e-01  7.07101330e-01]
 [ 7.02419162e-01 -7.11763529e-01 -4.30630134e-07]]
Ma trận đường chéo D:
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 1.]]
Ma trận nghịch đảo P_inv:
[[-5.03288724e-01  5.03296911e-01  7.02419162e-01]
 [-4.96681741e-01  4.96688965e-01 -7.11763529e-01]
 [ 7.07107871e-01  7.07105691e-01 -8.61260269e-08]]
Ma trận A khôi phục từ P, D, và P_inv:
[[ 2.99998150e+00 -2.00001233e+00  2.43603489e-07]
 [-1.99998767e+00  3.00001850e+00  2.43598892e-07]
 [ 1.21800825e-06  1.21800366e-06  5.00000000e+00]]


**Ý tưởng thực hiện tìm ma trận chéo P và ma trận đường chéo D, Để tìm ma trận chéo P và ma trận đường chéo D cho một ma trận vuông A ,ta thực hiện các bước sau:**
1. Tìm giá trị riêng của và vector riêng của A
- Thuật toán Power Iteration: là một phương pháp lặp đơn giản và hiệu quả để tìm trị riêng (eigenvalue) lớn nhất về độ lớn (the largest eigenvalue in magnitude) và vector riêng (eigenvector) tương ứng của một ma trận vuông A. 
2. Các bước thực hiện:
- Tìm trị riêng và vector riêng: Sử dụng thuật toán Power Iteration để tìm trị riêng lớn nhất và vector riêng tương ứng ở hàm def eigen_power_iteration(). Sử dụng deflation để giảm bậc của ma trận và tìm các trị riêng và vector riêng còn lại.
- Xây dựng ma trận chéo P: Ma trận P được tạo bởi các vector riêng của ma trận A
- Xây dựng ma trận đường chéo D: Ma trận D là ma trận đường chéo được tạo bởi các trị riêng của ma trận A bằng các sử dụng thư viện np.diag
- Tính ma trận nghịch đảo P^-1: Sử dụng thư viện np.linalg.inv để tìm ma trận nghịch đảo của P

## Bài 2) Mở rộng:
- Tìm hiểu các hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả.
- Tìm hiểu và trình bày ứng dụng của chéo hóa.

In [10]:
def matrix_diag(A):
    # Tìm trị riêng, vector riêng
    eigenvalues, eigenvectors = np.linalg.eig(A)
    
    # Sắp xếp giảm dần theo trị riêng
    sorted_idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_idx]
    eigenvectors = eigenvectors[:, sorted_idx]
    
    P_matrix = eigenvectors
    P_inv_matrix = np.linalg.inv(P_matrix)
    D_matrix = np.diag(eigenvalues)
    
    return P_matrix, D_matrix, P_inv_matrix

if __name__=="__main__":
    # Nhập ma trận A
    n = int(input('Nhập N: '))
    A = np.zeros((n, n))
    print('Nhập ma trận A[' + str(n) + 'x' + str(n) + ']:')
    for i in range(n):
        for j in range(n):
            A[i][j] = float(input('a[' + str(i) + '][' + str(j) + ']='))

    print('Ma trận A:')
    print(A)

    P, D, P_inv = matrix_diag(A)
    
    # Hiển thị các ma trận kết quả
    print('Ma trận chéo P:')
    print(P)
    print('Ma trận đường chéo D:')
    print(D)
    print('Ma trận nghịch đảo P_inv:')
    print(P_inv)
    
    # Khôi phục lại ma trận A từ P, D, và P_inv
    A_reconstructed = np.dot(np.dot(P, D), P_inv)
    
    # Hiển thị ma trận A đã được khôi phục để kiểm tra tính chính xác
    print('Ma trận A khôi phục từ P, D, và P_inv:')
    print(A_reconstructed)

Nhập ma trận A[3x3]:
Ma trận A:
[[ 3. -2.  0.]
 [-2.  3.  0.]
 [ 0.  0.  5.]]
Ma trận chéo P:
[[ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]
 [ 1.          0.          0.        ]]
Ma trận đường chéo D:
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 1.]]
Ma trận nghịch đảo P_inv:
[[ 0.          0.          1.        ]
 [ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]]
Ma trận A khôi phục từ P, D, và P_inv:
[[ 3. -2.  0.]
 [-2.  3.  0.]
 [ 0.  0.  5.]]


1. Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả.
- numpy.linalg.eig: Hàm này trả về các trị riêng (eigenvalues) và vector riêng (eigenvectors) của ma trận A.
- numpy.argsort: Trả về các chỉ số của các trị riêng theo thứ tự tăng dần.
[:: -1] đảo ngược thứ tự để có thứ tự giảm dần.
- numpy.diag: Tạo ra một ma trận đường chéo từ một mảng.
- numpy.dot: Thực hiện nhân ma trận.
- So sánh kết quả: Sử dụng thư viện có sẵn để giải ở Bài 2 cho ra kết quả có sai số rất rất nhỏ (gần đúng) hơn so với giải thuần túy ở Bài 1

2. Tìm hiểu và trình bày ứng dụng của chéo hóa:
Chéo hóa ma trận là một kỹ thuật toán học mạnh mẽ với nhiều ứng dụng quan trọng trong khoa học và kỹ thuật. Từ việc giải hệ phương trình vi phân, phân tích dữ liệu, thiết kế hệ thống điều khiển đến tăng tốc độ tính toán, chéo hóa ma trận đóng một vai trò quan trọng trong việc giải quyết các bài toán phức tạp một cách hiệu quả:
- Giải Hệ Phương Trình Vi Phân Tuyến Tính
- Phân Tích Ma Trận và Giảm Kích Thước Dữ Liệu
- Phân Tích và Thiết Kế Hệ Thống Điều Khiển
- Giải Quyết Bài Toán Giá Trị Riêng
- Tăng Tốc Độ Tính Toán...vv